#this works!, do not change a character!
# this creates a service of type loadbalancer, for a given deployment.
# this work only using windows/minikube/local machine and not on AWS cloud
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dennisdeployment
  #namespace: clientns
spec:
  replicas: 3
  selector:
    matchLabels:
      name: denniscontainer
  template:
    metadata:
      labels:
        name: denniscontainer
    spec:
      containers:
      - name: denniscontainer
        image: docker.io/dockeridiotfool/spring-boot-dennis:latest
        ports:
        - name: http-server
          containerPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: dennisservice
  #namespace: clientns
  labels:
    app: denniscontainer
spec:
  ports:
  - port: 8084 #the port on which it is available via the external dns
    targetPort: http-server
  selector:
    app: denniscontainer
  type: LoadBalancer