#this works!, do not change a character!
# this creates a service of type loadbalancer, for a given deployment.
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dennisdeployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: denniscontainer
    spec:
      containers:
      - name: denniscontainer
        image: docker.io/dockeridiotfool/spring-boot-dennis
        ports:
        - name: http-server
          containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: dennisservice
  labels:
    app: denniscontainer
spec:
  ports:
  - port: 8084 #the port on which it is available via the external dns
    targetPort: http-server
    nodePort: 30002 #Not sure what this is for, if not specified it takes some value and appears as 8084:30002/TCP as the listed port of the service when using command kubectl get services -o wide
  selector:
    app: denniscontainer
  type: LoadBalancer
