---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-postgres-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: spring-boot-postgres-container
  template:
    metadata:
      labels:
        name: spring-boot-postgres-container
    spec:
      containers:
      - name: spring-boot-postgres-container
        env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_user
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_password
          - name: POSTGRES_HOST
            value: {{ template "postgresql.fullname" . }} # this value which is same as in statefulset.yaml metadata.name field, this value is set in _helpers.tpl
        image: dockeridiotfool/spring-boot-postgres
        ports:
        - name: http-server
          containerPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: spring-boot-postgres-service
  labels:
    app: spring-boot-postgres-container
spec:
  ports:
  - port: 8084 #the port on which it is available via the external dns
    targetPort: http-server
  selector:
    app: spring-boot-postgres-container
  type: LoadBalancer